language: go
go_import_path: github.com/mrlsd/go-benchmark-app
go:
  - 1.6
  - 1.7
  - tip
matrix:
  allow_failures:
    - go: tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge

script:
  - go build
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v vendor)
  - make coverprofiles

after_success:
  - gocovmerge *.coverprofile > merged.coverprofile
  - goveralls -coverprofile=merged.coverprofile -service=travis-ci
  - cp merged.coverprofile coverage.txt
  - bash <(curl -s https://codecov.io/bash)
