# Title for describing benchmarks
title = "CMS benchmarks"
# Benchmarks version
version = "0.1"
# Delay via try (sec)
delay = 5
# How much we should try
try = 2
# How long wait when application guaranteed runned (sec)
waittorun = 2

# ab benchmarks parametres
[ab]
concurency = 500
keepalive = false
requests = 1000

# wrk benchmarks parametres
[wrk]
connections = 5000
duration = 10
threads = 1000

# siege benchmarks parametres
[siege]
concurrent = 100
time = 10

# Applications parametres
[[app]]
title = "Iron pure & minimal"
path = "/home/evgeny/gb/apps/iron.sh"
