# Title for describing benchmarks
title = "CMS benchmarks"
# Benchmarks version
version = "0.1"
# Delay via try (sec)
delay = 60
# How much we should try
try = 5
# How long wait when application guaranteed runned (sec)
waittorun = 3

# ab benchmarks parametres
[ab]
concurency = 500
keepalive = false
requests = 1000

# wrk benchmarks parametres
[wrk]
connections = 5000
duration = 10
threads = 1000

# siege benchmarks parametres
[siege]
concurrent = 100
time = 10

# Applications parametres
[[app]]
title = "Iron pure & minimal"
path = "/home/evgeny/gb/apps/iron.sh"
url = "http://localhost:3000/"

[[app]]
title = "Nickel pure & minimal"
path = "/home/evgeny/gb/apps/nickel.sh"
url = "http://localhost:3000/"

[[app]]
title = "Iron CMS minimal"
path = "/home/evgeny/gb/apps/iron-cms.sh"
url = "http://localhost:3000/"

[[app]]
title = "Nickel CMS minimal"
path = "/home/evgeny/gb/apps/nickel-cms.sh"
url = "http://localhost:3000/"