# Title for describing benchmarks
title = "CMS benchmarks"
# Benchmarks version
version = "0.1"
# Delay via try (sec)
delay = 5
# How much we should try
try = 10
# How long wait when application guaranteed runned (sec)
waittorun = 1

# ab benchmarks parametres
[ab]
concurency = 500
keepalive = false
requests = 1000

# wrk benchmarks parametres
[wrk]
connections = 5000
duration = 10
threads = 1000

# siege benchmarks parametres
[siege]
concurrent = 100
time = 30

# Applications parametres
[[app]]
title = "Iron pure & minimal"
path = "/home/evgeny/rs/iron/target/release/iron"

[[app]]
title = "Nickel pure & minimal"
path = "/home/evgeny/rs/nickel/target/release/nickel"

[[app]]
title = "Iron CMS"
path = "/home/evgeny/rs/iron-cms/target/release/iron-cms"

[[app]]
title = "Nickel CMS"
path = "/home/evgeny/rs/nickel-cms/target/release/nickel-cms"
